{% set name = "matbench-genmetrics" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/matbench-genmetrics-{{ version }}.tar.gz
  sha256: f0ba6ebb3a5253431212ce7682171accb920c76d18c7eb39414aac07ba548111

build:
  entry_points:
    - matbench-genmetrics = matbench_genmetrics.core:run
    - matbench_genmetrics = matbench_genmetrics.core:run
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - setuptools-scm
    - python >=3.6
  run:
    - matminer
    - mp-time-split
    - pymatgen
    - scipy
    - python >=3.6
    - importlib-metadata
test:
  imports:
    - matbench_genmetrics
  commands:
    - pip check
    - matbench-genmetrics --help
    - matbench_genmetrics --help
  requires:
    - pip

about:
  home: https://github.com/sparks-baird/matbench-genmetrics/
  summary: Generative materials benchmarking metrics, inspired by CDVAE.
  dev_url: https://github.com/sparks-baird/matbench-genmetrics
  license: MIT
  license_file:
    - LICENSE.txt
    - src/matbench_genmetrics/cdvae/LICENSE
  doc_url: matbench-genmetrics.readthedocs.io

extra:
  recipe-maintainers:
    - sgbaird
